### ISSUE TITLE
Consider adding hacs.json for https://hacs.xyz usage

### ISSUE THREAD

**Issue by tidalvirus** [ozczecho/custom_components#4]
I think adding a hacs.json file (and moving airtouch3 into a 'custom_components' folder in this repo) would be excellent for some users - this would simplify adding the custom component to Home Assistant to just 'add the repo', or even just 'search for airtouch3', if you decided to try and add it your repos into the default repository for HACS.

However, I do understand that you have multiple custom_components/integrations in this repo, and unless I'm mistaken, HACS only supports one integration/thing per repo - https://hacs.xyz/docs/publish/integration#repository-structure - and https://github.com/ludeeus/integration_blueprint (linked from the hacs.xyz docs) seems to imply that format as what would normally be expected.

Not sure how you might handle that? In the meantime, I forked and simply added a basic hacs.json file as a test, as well as moved airtouch3 to custom_components/airtouch3 - https://github.com/tidalvirus/custom_components

I didn't think it appropriate to make the fork a PR, because it would mean the other integrations are not visible for HACS usage.

Thanks again for this stuff - it's an excellent thing you've created!

**Comment by ozczecho** [comment]
Hi and thanks for the feedback.
TBH - it was a mistake from day 1 to bundle these integrations into 1 repo. It is not cool.Let me fix it up as it makes more sense for it to be in its own repo and also one code base.
I'll try and do it this week
Cheers
Mike

    On Monday, 24 July 2023 at 10:53:43 pm AEST, tidalvirus ***@***.***> wrote:  
 
 


I think adding a hacs.json file (and moving airtouch3 into a 'custom_components' folder in this repo) would be excellent for some users - this would simplify adding the custom component to Home Assistant to just 'add the repo', or even just 'search for airtouch3', if you decided to try and add it your repos into the default repository for HACS.

However, I do understand that you have multiple custom_components/integrations in this repo, and unless I'm mistaken, HACS only supports one integration/thing per repo - https://hacs.xyz/docs/publish/integration#repository-structure - and https://github.com/ludeeus/integration_blueprint (linked from the hacs.xyz docs) seems to imply that format as what would normally be expected.

Not sure how you might handle that? In the meantime, I forked and simply added a basic hacs.json file as a test, as well as moved airtouch3 to custom_components/airtouch3 - https://github.com/tidalvirus/custom_components

I didn't think it appropriate to make the fork a PR, because it would mean the other integrations are not visible for HACS usage.

Thanks again for this stuff - it's an excellent thing you've created!

**Comment by ozczecho** [comment]
`airtouch3` custom component now has its own repo: https://github.com/ozczecho/airtouch3_custom_component
